/*
 Navicat Premium Data Transfer

 Source Server         : root
 Source Server Type    : MySQL
 Source Server Version : 80036
 Source Host           : localhost:3306
 Source Schema         : biosecurity_guide

 Target Server Type    : MySQL
 Target Server Version : 80036
 File Encoding         : 65001

 Date: 10/03/2024 06:44:12
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for weed_guide
-- ----------------------------
DROP TABLE IF EXISTS `weed_guide`;
CREATE TABLE `weed_guide`  (
  `id` int NOT NULL AUTO_INCREMENT,
  `common name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `scientific name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `weed type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `impacts` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `control methods` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL,
  `primary image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `prImgLocalPath` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `image1` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `img1LocalPath` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `image2` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `img2LocalPath` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `image3` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  `img3LocalPath` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 26 CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci ROW_FORMAT = Dynamic;

-- ----------------------------
-- Records of weed_guide
-- ----------------------------
INSERT INTO `weed_guide` VALUES (1, 'Liliaceae (lily)', 'Agapanthus praecox', 'perennial plant', 'Robust, clump-forming perennial with long, thick, white rhizomes. Leathery, arching leaves (20-70 x 2-6 cm) with watery sap grow from the base in clumps of up to 20. Umbrella-shaped clusters (7 x 5 cm) of many small, purplish-blue or white flowers are produced from December to February, followed by thin, papery, black seeds.', 'Forms pure stands, excluding all other species and becoming the dominant species almost everywhere it grows. It causes massive biodiversity loss, especially of rare coastal herb, grass and shrub species.', 'Plants often resprout and seed bank reinfests bared sites thickly, so follow up frequently until eradicated. At least 3-4 follow up treatments are needed. Begin eradication at top of banks and work down. Don\'t replant until after 2-3 treatments.', 'https://www.weedbusters.org.nz/site/assets/files/1100/2006_0101weeds90002.800x700-ms.jpg', 'static/weed-images/Agapanthus_praecox_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1100/dscf5642.800x700-ms.jpg', 'static/weed-images/Agapanthus_praecox_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1100/2007_1210coroxmas07x20018.800x700-ms.jpg', 'static/weed-images/Agapanthus_praecox_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1100/2005_1125aggies0043.800x700-ms.jpg', 'static/weed-images/Agapanthus_praecox_img3.jpg');
INSERT INTO `weed_guide` VALUES (2, 'Lamiaceae (mint)', 'Lamium galeobdolon', 'invasive species', 'Vigorous, perennial, mat-forming groundcover, with square, purplish stems and stolons that are densely hairy. Pleasant smelling, mint-like oval leaves (30-80 x 25-60 mm) are hairy below with large, pale, silvery-grey patches on upper surface, coarsely serrated along the edges, and arranged alternately on the stems. It is often found in gardens growing in the cooler areas around trees and shrubs. Tubular, hairy, lemon-yellow flowers (20-25 mm long) are produced (Dec-May) in dense whorls where leaf stems join main stems, but no seed is set. Plants seldom revert to plain green-leaved form.', 'Forms dense groundcover and prevents seedlings of native species establishing.', 'Follow up required 3-monthly until eradication achieved. No seedlings are produced, so eradication is possible.', 'https://www.weedbusters.org.nz/site/assets/files/1197/lamium_galeobdolon_t.800x700-ms.jpg', 'static/weed-images/Lamium_galeobdolon_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1197/lamium_galeobdolon_p.800x700-ms.jpg', 'static/weed-images/Lamium_galeobdolon_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1197/2005_1003olives20006.800x700-ms.jpg', 'static/weed-images/Lamium_galeobdolon_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1197/lamium_galeobdolon_l.225x225.jpg', 'static/weed-images/Lamium_galeobdolon_img3.jpg');
INSERT INTO `weed_guide` VALUES (3, 'Asteraceae (daisy)', 'Bartlettina sordida', 'invasive species', 'Erect shrub (<2 m), woody at base, with stems covered in reddish-purple striped down. Densely-hairy leaves (11-25 x 8-25 cm) are opposite. Fluffy, purplish-pink flowers (Nov-Jan) are followed by tiny, husky seeds.', 'Limited damage as it occupies forest edges, inhibiting regeneration.', 'Resprouts after slashing. Easy to manage. Seedlings do not compete aggressively for space. Replant bared areas to prevent seedlings.', 'https://www.weedbusters.org.nz/site/assets/files/1116/2005_1025weeds30013.800x700-ms.jpg', 'static/weed-images/Bartlettina_sordida_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1116/dscf0303.800x700-ms.jpg', 'static/weed-images/Bartlettina_sordida_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1116/dscf5657.800x700-ms.jpg', 'static/weed-images/Bartlettina_sordida_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1116/2005_1025weeds30014.800x700-ms.jpg', 'static/weed-images/Bartlettina_sordida_img3.jpg');
INSERT INTO `weed_guide` VALUES (4, 'Rosaceae (rose)', 'Rubus fruticosus', 'perennial plants', 'Scrambling, very thorny, semi-erect shrub that is usually deciduous, with large root crowns and long suckers. Stems arching (occasionally semi-prostrate), entangled, green or red and occasionally taking root when in contact with the ground. Variously shaped (usually cut-edged), flat leaves are arranged alternately on the stems. White to pink 5-petalled flowers (Nov-Apr) followed by clusters of black berries (Nov-May).', 'Low to moderate damage in open habitats. Smothers most low growing species, inhibiting the establishment of native plant seedings, and impedes access.', 'Recovers quickly after slashing or grazing, rhizomes are difficult to dig out and always regrow. Native species will usually overtop blackberry if good canopy growth. Spray at least 4 months before replanting with other species', 'https://www.weedbusters.org.nz/site/assets/files/1246/dscf4395.800x700-ms.jpg', 'static/weed-images/Rubus_fruticosus_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1246/dscf5555.800x700-ms.jpg', 'static/weed-images/Rubus_fruticosus_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1246/rubus_fruticosus_aj.800x700-ms.jpg', 'static/weed-images/Rubus_fruticosus_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1246/dscf5555.800x700-ms.jpg', 'static/weed-images/Rubus_fruticosus_img3.jpg');
INSERT INTO `weed_guide` VALUES (5, 'Alstroemeriaceae (alstroemeria)', 'Bomarea multiflora', 'multi-stemmed vine', 'Multi-stemmed, scrambling, perennial vine that twines around any available support and may die back over winter in frost-prone localities. Stems arise from short underground rhizomes that bear numerous tubers. Leaves are long and pointed, with parallel vines. Tubular flowers range from red to orange or gold on the outside and yellow inside with dark spots, and hang in clusters of 15-20 flowers from summer to winter. Numerous fleshy, round, bright orange fruit develop in a capsule (2 cm diameter) from May to August.', 'Smothers and kills supporting trees, and prevent the growth of native seedlings and understorey plants by blocking their light. Seedlings are capable of growing in the forest interior and will creep along the ground, strangling saplings and smothering low-growing species.', 'Monitor the site and treat any regrowth from rhizomes or seedlings. Where appropriate plant a local native shrub, tree or climber.', 'https://www.weedbusters.org.nz/site/assets/files/1119/dscf5852.800x700-ms.jpg', 'static/weed-images/Bomarea_multiflora_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1119/dscf5849.800x700-ms.jpg', 'static/weed-images/Bomarea_multiflora_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1119/dscf4519.800x700-ms.jpg', 'static/weed-images/Bomarea_multiflora_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1119/bomarea_multiflora_ba.800x700-ms.jpg', 'static/weed-images/Bomarea_multiflora_img3.jpg');
INSERT INTO `weed_guide` VALUES (6, 'Buddlejaceae (buddleia)', 'Buddleja davidii', 'Broadleaf', 'Deciduous (occasionally semi-evergreen) open, multi-stemmed shrub (<3+ m tall). Stems are bluntly angled, clad in tufts of easily-removed soft woolly hair (downy hairs when young), and become lax when long. Thin, willow-shaped leaves (6-20 x 3-8 cm) are usually hairless above, white or hairy grey underneath, and finely toothed. Distinctive, dense, cone-shaped hanging clusters (30 x 5 cm) made up of many fragrant purple or white flowers (5 mm diameter, Dec-Feb) with orange insides are followed by seed capsules (5-10 mm long).', 'Forms dense stands in wide range of habitats. In riverbeds it can alter water flow, causing silt buildup and flooding.', 'Seed bank reinfests bared sites. Cut stumps resprout. Difficult to prevent reinvasion. Follow up 6-monthly. Maintain rolling front.', 'https://www.weedbusters.org.nz/site/assets/files/1121/2003_0125weeds0026.800x700-ms.jpg', 'static/weed-images/Buddleja_davidii_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1121/dscf5691.800x700-ms.jpg', 'static/weed-images/Buddleja_davidii_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1121/dscf4824.800x700-ms.jpg', 'static/weed-images/Buddleja_davidii_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1121/dscf4405.800x700-ms.jpg', 'static/weed-images/Buddleja_davidii_img3.jpg');
INSERT INTO `weed_guide` VALUES (7, 'Papaveraceae (poppy)', 'Eschscholzia californica', 'invasive species', 'Annual or perennial herb growing as a small tufted rosette, or an erect branched plant (30-60 cm) with ribbed stems and grey or blue-green, much divided leaves (<10 cm x 10 cm). Produces individual yellow to orange flowers (spring and summer) with four overlapping petals (2-6 cm long) that only open in sunlight and that are followed by ribbed seed capsules (3-9 cm) that split in two to release numerous small black or dark brown seeds.', 'Outcompetes small native grasses and herbs on poor soils.', 'Where appropriate plant local native plants to shade out seedlings', 'https://www.weedbusters.org.nz/site/assets/files/1164/dscf0298.800x700-ms.jpg', 'static/weed-images/Eschscholzia_californica_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1164/dscf1943.800x700-ms.jpg', 'static/weed-images/Eschscholzia_californica_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1164/eschscholzia_californica_al.800x700-ms.jpg', 'static/weed-images/Eschscholzia_californica_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1164/dscf0106.800x700-ms.jpg', 'static/weed-images/Eschscholzia_californica_img3.jpg');
INSERT INTO `weed_guide` VALUES (8, 'Cannaceae (canna lily)', 'Canna indica', 'perennial plants', 'Erect, leafy perennial herb (<2 m tall) with thick underground stems (rhizomes) and sturdy, unbranched, green and hairless above-ground stems from which large, green (sometimes purple tinged), oblong leaves (<45 cm long x 15 cm wide) with prominent midribs grow. Pinkish-red to reddish-yellow and occasionally yellow or orange-red flowers (5-6 cm long) grow from the top of the stem, often in pairs, followed by round seed capsules (2 cm diameter) containing round black seeds.', 'Replaces all other plants on the ground, preventing natural regeneration, often leading to the invasion of weedy vines. Removes water from damp habitats.', 'Fragments remaining in soil will resprout so followup control by digging or spraying is required. Plant the site with local native plants to shade out seedlings.', 'https://www.weedbusters.org.nz/site/assets/files/1123/canna_indica_n.800x700-ms.jpg', 'static/weed-images/Canna_indica_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1123/dscf2213.800x700-ms.jpg', 'static/weed-images/Canna_indica_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1123/canna_indica_q.800x700-ms.jpg', 'static/weed-images/Canna_indica_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1123/canna_indica_h.800x700-ms.jpg', 'static/weed-images/Canna_indica_img3.jpg');
INSERT INTO `weed_guide` VALUES (9, 'Oleaceae (olive)', 'Ligustrum sinense', 'invasive species', 'Shrub or small tree (<5+ m), evergreen or semi-deciduous in cold districts with distinctive warty lumps on stems and densely hairy shoots. Oval, dull green leaves (25-60 x 12-25 mm) occasionally have wavy edges. Loose drooping clusters (<10 cm long) of small, tubular and very fragrant white flowers with tiny mauve anthers (Jul-Mar) are followed by round, green berries that mature to dull purplish-black.', 'Dense stands prevent the establishment of native plant seedlings and displace vulnerable native shrub species. Poisonous berries may possibly impact on native fauna, especially insects.', 'Untreated stumps resprout quickly. Bared areas reseed profusely. Follow up 6-monthly, easiest to spot during spring flowering. Replant bared areas to minimise seedling growth.', 'https://www.weedbusters.org.nz/site/assets/files/1201/dscf4692.800x700-ms.jpg', 'static/weed-images/Ligustrum_sinense_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1201/2005_1121ellerslie050030.800x700-ms.jpg', 'static/weed-images/Ligustrum_sinense_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1201/dscf4690.800x700-ms.jpg', 'static/weed-images/Ligustrum_sinense_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1201/dscf4692.800x700-ms.jpg', 'static/weed-images/Ligustrum_sinense_img3.jpg');
INSERT INTO `weed_guide` VALUES (10, 'Fabaceae (legume)', 'Psoralea pinnata', 'invasive species', 'Evergreen short-lived shrub (<2 m, occasionally <5 m) with erect, much-branched, soft-woody stems that are hairy and ribbed when young. Leaves (15-40 mm long) are each divided into 2-4 opposite pairs of leaflets and a terminal leaflet, all similar to pine needles. Solitary or small clusters of pea-like blue-white or mauve-white flowers (13 mm diameter, Nov-Jan) are followed by hairless, wrinkled seed pods (4-5 mm long) each containing one dark brown seed.', 'Dominates low canopy habitats, delaying (occasionally preventing) the establishment of native plant seedlings. Increased nitrogen in gumlands and other impoverished soil types may change the species that are present and resulting change in habitat may be to the detriment of specialised plants eg. orchids, ferns, herbs, etc, or encourage further weed invasions. Can replace manuka in successional process.', 'Cut stems resprout. Never use fire as a management tool. In regenerating bush habitats over 4 m this plant is normally succeeded by tall-growing native species. Where plant is dense (ie. no native species present), possibly encourage regeneration with partial and selective control methods. Control in low-growing habitats and vector corridors (quarries, roadsides, etc).', 'https://www.weedbusters.org.nz/site/assets/files/1239/house_and_plants_028.800x700-ms.jpg', 'static/weed-images/Psoralea_pinnata_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1239/dscf9961.800x700-ms.jpg', 'static/weed-images/Psoralea_pinnata_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1239/psoralea_pinnata_x.800x700-ms.jpg', 'static/weed-images/Psoralea_pinnata_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1239/dscf8750.800x700-ms.jpg', 'static/weed-images/Psoralea_pinnata_img3.jpg');
INSERT INTO `weed_guide` VALUES (11, 'Hydrocharitaceae (frogbit)', 'Egeria densa', 'invasive species', 'Submerged, bottom-rooting perennial (<5 m). Slender, brittle, buoyant stems (3 mm diameter) are much-branched. Linear, dark green leaves (15-30 x 4 mm) are in whorls of 4-6 (occasionally 3 near base). From November to January it produces flowers (20 mm diameter) that are white, 3-petalled with yellow stamens, and that sit on the surface of the water. As only male plants are found in New Zealand, no seed is set.', 'Forms vast underwater \'meadows\', shades out smaller native species, and prevents seedlings of native species establishing. Large clumps can dislodge from the underwater \'meadows\', causing flooding. Rotting vegetation stagnates water, killing fauna and flora.', 'In small ponds, this plant can be killed by first using mechanical clearance, taking care not to spread fragments, followed by bottom lining of the pond. For larger infestations or infestations in flowing water, contact your regional council or local Department of Conservation office for advice.', 'https://www.weedbusters.org.nz/site/assets/files/1154/egeria_shoot_rw.800x700-ms.jpg', 'static/weed-images/Egeria_densa_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1154/egeria_densa_c.800x700-ms.jpg', 'static/weed-images/Egeria_densa_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1154/egeria_densa_b.800x700-ms.jpg', 'static/weed-images/Egeria_densa_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1154/egeria_densa_jpg_2.800x700-ms.jpg', 'static/weed-images/Egeria_densa_img3.jpg');
INSERT INTO `weed_guide` VALUES (12, 'Araceae (arum)', 'Alocasia brisbanensis', 'ornamental plants', 'Large perennial (<3 m tall) with a thick, fleshy rhizome with milky sap. Mature plants have thick, trunk-like stems (5 m x 30 cm) with leaf scars and the lower part of the stem usually lies along the ground. Shiny, leathery, deep green arrow-shaped leaves (80 x 50 cm) have prominent veins, and occasionally have white patches. Fragrant creamy-yellow to orange flower spikes (<15 cm long) are held inside green boat-shaped bracts (<5 cm long) and develop into scarlet or orange berries.', 'Smothers the ground, preventing the seedlings of native species from establishing. It is unlikely to poison native fauna.', 'Digging usually leaves rhizome fragments and plants will always regrow after slashing. Exclude all livestock from site when treating. Follow up annually.', 'https://www.weedbusters.org.nz/site/assets/files/1106/dscf4045.800x700-ms.jpg', 'static/weed-images/Alocasia_brisbanensis_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1106/dscf4021.800x700-ms.jpg', 'static/weed-images/Alocasia_brisbanensis_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1106/dscf4890.800x700-ms.jpg', 'static/weed-images/Alocasia_brisbanensis_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1106/dscf4005.800x700-ms.jpg', 'static/weed-images/Alocasia_brisbanensis_img3.jpg');
INSERT INTO `weed_guide` VALUES (13, 'Poaceae (grass)', 'Nassella tenuissima', 'invasive species', 'Very fine grass with extremely tough, thin, round blades that don\'t break when pulled, and are rough to touch. Drooping flowering stems with open seedheads appear in spring, and the seeds give the plant a purplish-pink tinge when they ripen.', 'Forms pure stands in low-growing plant communities, especially in harsh sites, and prevent the seedlings of native species establishing.', 'Cut rootstock and roots not completely grubbed from soil will resprout, and seed bank reinfests bared, burned or sprayed areas. Fire enhances seeding. Do not burn as fire enhances seedings, and exclude all livestock. Plant dense low cover where appropriate after control. Follow up on open sites for at least 10 years.', 'https://www.weedbusters.org.nz/site/assets/files/1216/2007_0220weedspmi20006.800x700-ms.jpg', 'static/weed-images/Nassella_tenuissima_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1216/dscf4474.800x700-ms.jpg', 'static/weed-images/Nassella_tenuissima_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1216/2007_0220weedspmi20002.800x700-ms.jpg', 'static/weed-images/Nassella_tenuissima_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1216/2007_0727wellington0004.800x700-ms.jpg', 'static/weed-images/Nassella_tenuissima_img3.jpg');
INSERT INTO `weed_guide` VALUES (14, 'Fabaceae (pea)', 'Ulex europaeus', 'invasive species', 'Sharply spiny shrub (<2-3 m tall) with woody erect or spreading stems which are many-branched in younger plants but become bare at the base as the plant gets older. Leaves are reduced to spines, new leaves less so. Spines are deeply furrowed. Pea-like yellow flowers (13-20 mm long, May-Nov, sometimes all year) are followed by hairy seed pods (13-25 mm long) which turn black when mature and explode to release seeds.', 'Forms pure associations temporarily in many habitats, inhibiting the establishment of native plant seedlings. Increased nitrogen in poor soil types changes native species able to grow there. Can be a nursery crop for native species, dying back when overtopped, but less likely on dry sites.', 'Stumps resprout quickly. Reseeds profusely, especially after fire, disturbance or non-selective spraying. Do not burn or graze. Only use glyphosate spray when all vegetation on site is to be bared for replanting (generally not recommended). Maintain humus layer. Sites with appropriate tall forest species present can usually be left to be overtopped, can speed by selective slashing, stump swabbing or planting. Maintain roadsides, cuttings and other vectors, check road gravel and fill.', 'https://www.weedbusters.org.nz/site/assets/files/1269/ulex_europaeus_ax_ls.800x700-ms.jpg', 'static/weed-images/Ulex_europaeus_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1269/ulex_europaeus_bi.800x700-ms.jpg', 'static/weed-images/Ulex_europaeus_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1269/ulex_europaeus_ce.800x700-ms.jpg', 'static/weed-images/Ulex_europaeus_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1269/ulex_europaeus_v.800x700-ms.jpg', 'static/weed-images/Ulex_europaeus_img3.jpg');
INSERT INTO `weed_guide` VALUES (15, 'Ceratophyllaceae (hornwort)', 'Ceratophyllum demersum', 'unwanted organism', 'Submerged, free-floating or anchored perennial that grows in water up to 16m deep. No roots are present, and it is usually lightly anchored by buried stems and leaves. Stems (30-150 cm long) are floating or submerged, branched, stiff and brittle. Thin dark green leaves (1-4 cm long) in whorls of 7-12 are densely crowded at the stem tip, increasingly spaced down the stem, and equally forked once or twice into stiff tapering segments with teeth on the outer edge. Produces minute green or white flowers, but is not known to fruit in New Zealand.', 'Forms dense beds, shades out smaller native species and prevents them establishing. It can contribute to blockages of waterways and flooding. Rotting vegetation stagnates water, killing fauna and flora. Threatens most submerged plant communities.', 'Report all sites to your regional council or local Department of Conservation office.', 'https://www.weedbusters.org.nz/site/assets/files/1130/ceratophyllum_d_rw.800x700-ms.jpg', 'static/weed-images/Ceratophyllum_demersum_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1130/ceratophyllum_demersum_rw2.800x700-ms.jpg', 'static/weed-images/Ceratophyllum_demersum_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1130/ceratophyllum_demersum_8_m_rw.225x225.jpg', 'static/weed-images/Ceratophyllum_demersum_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1130/hornwort_underwater_niwa_jpg.225x225.jpg', 'static/weed-images/Ceratophyllum_demersum_img3.jpg');
INSERT INTO `weed_guide` VALUES (16, 'Aizoaceae (fig-marigold)', 'Carpobrotus edulis', 'invasive species', 'Low-growing, mat forming perennial with fleshy, succulent, 3-angled leaves (7-12 cm long) and 2-angled stems. Many-petalled yellow flowers (<10 cm diameter, mostly Oct-Feb) that turn pinkish-orange with age develop into fleshy fruit containing seed. Can hybridise with the native Disphyma australe to produce smaller plants (leaves 2-6 cm long) with orange-pink or yellow-whitish flowers (4.5-6cm diameter), turning pink with a yellow base with age. No fruit is formed.', 'Hybridises with and replaces the native ice plant (Disphyma australe). Forms mats over sand dunes and open areas, displacing other vegetation and changing the structure of sand dunes by preventing sand movement and hindering the natural processes of disturbance and change in dune environments. Reduces soil pH and influences soil nutrients, and can produce a build-up of organic matter in normally sandy soils, leading to other non-native species being able to establish.', 'Monitoring and follow-up control will be required to prevent seedling establishment. Revegetate dune area with native dune plants.', 'https://www.weedbusters.org.nz/site/assets/files/1125/carpobrotus_edulis_b.800x700-ms.jpg', 'static/weed-images/Carpobrotus_edulis_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1125/carpobrotus_edulis_2.800x700-ms.jpg', 'static/weed-images/Carpobrotus_edulis_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1125/carpobrotus_edulis_l.800x700-ms.jpg', 'static/weed-images/Carpobrotus_edulis_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1125/carpobrotus_edulis_2.800x700-ms.jpg', 'static/weed-images/Carpobrotus_edulis_img3.jpg');
INSERT INTO `weed_guide` VALUES (17, 'Oleaceae (olive)', 'Jasminum polyanthum', 'evergreen climbing vine', 'Perennial, evergreen, climbing, almost hairless, non-woody vine with very long, round, tough, stems that root at nodes. Smooth edged leaves are arranged in opposite pairs on stems, and are divided along the midvein into usually 7 leaflets with the terminal leaflet (<7 x 2.5 cm) the largest. Clustered, tube-like white flowers that are pink when in bud and very fragrant (Jan-Dec), are very rarely followed by glossy black berries (5-8 mm diameter).', 'Smothers and kills all plants from ground level to medium to highly canopy, and prevents the establishment of native plant seedlings. Ingress into established forest is rapid via ground or canopy.', 'Stumps resprout very quickly, cut stems root at nodes. Many plants appear not to produce seed, however once established jasmine is hard to kill and dispose of. Always dry and burn or deeply bury all cut material.', 'https://www.weedbusters.org.nz/site/assets/files/1195/jasminum_polyanthum_ac.800x700-ms.jpg', 'static/weed-images/Jasminum_polyanthum_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1195/2003_0126aucklandweeds0003.800x700-ms.jpg', 'static/weed-images/Jasminum_polyanthum_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1195/dscf4593.800x700-ms.jpg', 'static/weed-images/Jasminum_polyanthum_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1195/2005_0805whangamatasept050037.800x700-ms.jpg', 'static/weed-images/Jasminum_polyanthum_img3.jpg');
INSERT INTO `weed_guide` VALUES (18, 'Fabaceae (pea)', 'Acacia paradoxa', 'invasive species', 'Shrub or small tree (<3 m tall) with furrowed twigs that are moderately hairy. Leaves (10-18 x 2-8 mm) reduced to small, oval, asymmetric flaps on stem and thin stiff spines at base. Clusters of 5+ small, golden, pea-sized flowers (Jul-Oct) are followed by hairy, straight or curved seed pods (40-50 x 3-4 mm).', 'Forms tall, dense, impenetrable stands in disturbed and bare sites, preventing native species establishing. Fixes nitrogen so may affect ability of specialised low-fertility native plant communities (ferns, orchids, kauri, etc) to grow.', 'Can be succeeded in tall canopy habitats by taller native species (not in kauri or tanekaha forest). These sites can be left, regeneration can be speeded by slashing, selective spraying or replanting of shade-creating species. Clear roads, quarries. Maintain pest and livestock control, as plant is not readily grazed.', 'https://www.weedbusters.org.nz/site/assets/files/1281/acacia_paradoxum_j.800x700-ms.jpg', 'static/weed-images/Acacia_paradoxa_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1281/acacia_paradoxum_i.800x700-ms.jpg', 'static/weed-images/Acacia_paradoxa_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1281/acacia_paradoxum_z.800x700-ms.jpg', 'static/weed-images/Acacia_paradoxa_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1281/dscf1970.800x700-ms.jpg', 'static/weed-images/Acacia_paradoxa_img3.jpg');
INSERT INTO `weed_guide` VALUES (19, 'Verbenaceae (teak, verbena, puriri)', 'Lantana camara var. aculeata', 'Verbenaceae', 'Smelly scrambling evergreen shrub (<4-5 m) with woody taproot with laterals that sucker when broken. Young stems are 4-angled, hairy and prickly, and older stems are rounded, woody, much branched, and brittle. Hairy, ovalish leaves (3-9 cm long) in opposite pairs along the stems, very wrinkled, and have toothed edges. Conspicuous flat flower heads (2-3 cm across, all year round) with many tiny tubular flowers, each cream, yellow, orange, pink, red, purple or mixtures of these, changing colour as they mature, are followed by small, clustered, berry-like fruits, green ripening to juicy purple-black, contain one small pale seed per fruit.', 'Totally smothers and replaces all other species on the ground, causing permanent loss of habitat.', 'Physical removal largely ineffective as root fragments sucker where broken. Cut stems resprout. Recovers well after fire. Reseeds in bared areas after spraying. Avoid root disturbance if possible when controlling. Check all treated sites for seedlings and suckers. Don\'t replant for two years after all plants destroyed. Seed longevity usually low. Replant with dense cover and constantly check for new seedlings.', 'https://www.weedbusters.org.nz/site/assets/files/1198/lantana_camara_f.800x700-ms.jpg', 'static/weed-images/Lantana_camara_var._aculeata_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1198/2007_0607northland070023.800x700-ms.jpg', 'static/weed-images/Lantana_camara_var._aculeata_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1198/lantana_camara_ad.800x700-ms.jpg', 'static/weed-images/Lantana_camara_var._aculeata_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1198/lantana_camara_m.800x700-ms.jpg', 'static/weed-images/Lantana_camara_var._aculeata_img3.jpg');
INSERT INTO `weed_guide` VALUES (20, 'Asteraceae (daisy)', 'Senecio glastifolius', 'perennial herb', 'Upright perennial (<1 m tall) with oval, coarsely toothed, light green leaves and cluster of bright pink, purple, or mauve, daisy-like flowers with yellow centres (Sep-Nov). Downy, wind-spread seeds.', 'Poisonous to stock, takes over large areas of pasture, grassland, cliffs and dune sites.', 'Pull out the plant and dispose of any seedheads to prevent spread.', 'https://www.weedbusters.org.nz/site/assets/files/1303/dscf0433.800x700-ms.jpg', 'static/weed-images/Senecio_glastifolius_primaryimg.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1303/dscf0431.800x700-ms.jpg', 'static/weed-images/Senecio_glastifolius_img1.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1303/dscf8503.800x700-ms.jpg', 'static/weed-images/Senecio_glastifolius_img2.jpg', 'https://www.weedbusters.org.nz/site/assets/files/1303/senecio_glastifolius_z.800x700-ms.jpg', 'static/weed-images/Senecio_glastifolius_img3.jpg');
INSERT INTO `weed_guide` VALUES (25, 'fdsafdas', 'fdsafdsa', 'fdsasd', 'fdsaf', '', 'fdsafdsa', NULL, 'static/weed-images/fdsafdsa_primaryimg.jpg', NULL, 'static/weed-images/fdsafdsa_img1.jpg', NULL, 'static/weed-images/fdsafdsa_img2.jpg', NULL, 'static/weed-images/fdsafdsa_img3.jpg');

SET FOREIGN_KEY_CHECKS = 1;
